import { FileText, Building2, Wrench, Key, Search, PenTool, Hammer, ClipboardCheck } from "lucide-react"

export const projectTimelines = {
  "blantyre-commercial-complex": [
    {
      id: "planning",
      title: "Planning & Design Phase",
      description: "Initial project planning, site analysis, and architectural design development",
      startDate: "Jan 2022",
      endDate: "Apr 2022",
      duration: "4 months",
      status: "completed" as const,
      milestones: [
        {
          id: "site-analysis",
          title: "Site Analysis & Feasibility Study",
          date: "Jan 15, 2022",
          description: "Comprehensive site evaluation and project feasibility assessment",
          status: "completed" as const,
          icon: <Search className="h-4 w-4 text-primary" />,
        },
        {
          id: "design-approval",
          title: "Architectural Design Approval",
          date: "Mar 10, 2022",
          description: "Final architectural plans approved by client and authorities",
          status: "completed" as const,
          icon: <PenTool className="h-4 w-4 text-primary" />,
        },
        {
          id: "permits",
          title: "Building Permits Obtained",
          date: "Apr 5, 2022",
          description: "All necessary building permits and approvals secured",
          status: "completed" as const,
          icon: <FileText className="h-4 w-4 text-primary" />,
        },
      ],
      deliverables: [
        "Site analysis report",
        "Architectural drawings",
        "Structural engineering plans",
        "Building permits",
        "Project timeline",
        "Budget estimates",
      ],
      team: ["James Mbewe", "Sarah Banda", "Michael Phiri", "David Chirwa"],
    },
    {
      id: "foundation",
      title: "Foundation & Structure",
      description: "Excavation, foundation work, and structural framework construction",
      startDate: "May 2022",
      endDate: "Sep 2022",
      duration: "5 months",
      status: "completed" as const,
      milestones: [
        {
          id: "excavation",
          title: "Site Excavation Completed",
          date: "May 20, 2022",
          description: "Site preparation and excavation work finished",
          status: "completed" as const,
          icon: <Hammer className="h-4 w-4 text-primary" />,
        },
        {
          id: "foundation-complete",
          title: "Foundation Work Completed",
          date: "Jul 15, 2022",
          description: "All foundation and basement work completed",
          status: "completed" as const,
          icon: <Building2 className="h-4 w-4 text-primary" />,
        },
        {
          id: "structure-complete",
          title: "Structural Framework Complete",
          date: "Sep 10, 2022",
          description: "Main structural framework and floors completed",
          status: "completed" as const,
          icon: <Building2 className="h-4 w-4 text-primary" />,
        },
      ],
      deliverables: [
        "Foundation completion certificate",
        "Structural inspection reports",
        "Quality control documentation",
        "Progress photographs",
        "Updated project schedule",
      ],
      team: ["Michael Phiri", "David Chirwa", "Construction Crew", "Structural Engineers"],
    },
    {
      id: "construction",
      title: "Construction & Fit-out",
      description: "Building construction, MEP installation, and interior fit-out work",
      startDate: "Oct 2022",
      endDate: "Apr 2023",
      duration: "7 months",
      status: "completed" as const,
      milestones: [
        {
          id: "envelope-complete",
          title: "Building Envelope Completed",
          date: "Dec 20, 2022",
          description: "Exterior walls, windows, and roofing completed",
          status: "completed" as const,
          icon: <Building2 className="h-4 w-4 text-primary" />,
        },
        {
          id: "mep-installation",
          title: "MEP Systems Installation",
          date: "Feb 15, 2023",
          description: "Mechanical, electrical, and plumbing systems installed",
          status: "completed" as const,
          icon: <Wrench className="h-4 w-4 text-primary" />,
        },
        {
          id: "interior-fitout",
          title: "Interior Fit-out Completed",
          date: "Apr 10, 2023",
          description: "All interior finishes and fixtures completed",
          status: "completed" as const,
          icon: <PenTool className="h-4 w-4 text-primary" />,
        },
      ],
      deliverables: [
        "MEP system certifications",
        "Interior design completion",
        "Fire safety system installation",
        "Elevator installation and testing",
        "Parking facility completion",
      ],
      team: ["Michael Phiri", "Patricia Kamoto", "MEP Contractors", "Interior Designers"],
    },
    {
      id: "completion",
      title: "Testing & Handover",
      description: "Final inspections, testing, and project handover to client",
      startDate: "May 2023",
      endDate: "Jun 2023",
      duration: "2 months",
      status: "completed" as const,
      milestones: [
        {
          id: "final-inspection",
          title: "Final Building Inspection",
          date: "May 15, 2023",
          description: "Comprehensive building inspection and compliance verification",
          status: "completed" as const,
          icon: <ClipboardCheck className="h-4 w-4 text-primary" />,
        },
        {
          id: "occupancy-certificate",
          title: "Occupancy Certificate Issued",
          date: "May 30, 2023",
          description: "Official occupancy certificate obtained from authorities",
          status: "completed" as const,
          icon: <FileText className="h-4 w-4 text-primary" />,
        },
        {
          id: "handover",
          title: "Project Handover",
          date: "Jun 15, 2023",
          description: "Official project handover to client with all documentation",
          status: "completed" as const,
          icon: <Key className="h-4 w-4 text-primary" />,
        },
      ],
      deliverables: [
        "Occupancy certificate",
        "Warranty documentation",
        "Operation and maintenance manuals",
        "As-built drawings",
        "Final project report",
        "Handover certificate",
      ],
      team: ["James Mbewe", "Sarah Banda", "David Chirwa", "Quality Assurance Team"],
    },
  ],
  "limbe-residential-estate": [
    {
      id: "planning",
      title: "Master Planning & Design",
      description: "Estate master planning, architectural design, and regulatory approvals",
      startDate: "Mar 2021",
      endDate: "Jul 2021",
      duration: "5 months",
      status: "completed" as const,
      milestones: [
        {
          id: "master-plan",
          title: "Master Plan Development",
          date: "Apr 10, 2021",
          description: "Comprehensive estate master plan and layout design",
          status: "completed" as const,
          icon: <PenTool className="h-4 w-4 text-primary" />,
        },
        {
          id: "house-designs",
          title: "House Design Approval",
          date: "May 25, 2021",
          description: "Individual house designs and specifications approved",
          status: "completed" as const,
          icon: <Building2 className="h-4 w-4 text-primary" />,
        },
        {
          id: "approvals",
          title: "Regulatory Approvals",
          date: "Jul 15, 2021",
          description: "All planning permissions and development approvals obtained",
          status: "completed" as const,
          icon: <FileText className="h-4 w-4 text-primary" />,
        },
      ],
      deliverables: [
        "Estate master plan",
        "Individual house designs",
        "Infrastructure layout plans",
        "Environmental impact assessment",
        "Development permits",
      ],
      team: ["James Mbewe", "Grace Mwale", "Michael Phiri", "Urban Planners"],
    },
    {
      id: "infrastructure",
      title: "Infrastructure Development",
      description: "Site preparation, utilities installation, and road construction",
      startDate: "Aug 2021",
      endDate: "Dec 2021",
      duration: "5 months",
      status: "completed" as const,
      milestones: [
        {
          id: "site-prep",
          title: "Site Preparation",
          date: "Aug 20, 2021",
          description: "Land clearing, grading, and site preparation completed",
          status: "completed" as const,
          icon: <Hammer className="h-4 w-4 text-primary" />,
        },
        {
          id: "utilities",
          title: "Utilities Installation",
          date: "Oct 15, 2021",
          description: "Water, sewer, and electrical infrastructure installed",
          status: "completed" as const,
          icon: <Wrench className="h-4 w-4 text-primary" />,
        },
        {
          id: "roads",
          title: "Road Construction",
          date: "Dec 10, 2021",
          description: "Internal roads and walkways construction completed",
          status: "completed" as const,
          icon: <Building2 className="h-4 w-4 text-primary" />,
        },
      ],
      deliverables: [
        "Utility infrastructure completion",
        "Road construction completion",
        "Drainage system installation",
        "Street lighting installation",
        "Landscaping preparation",
      ],
      team: ["Michael Phiri", "David Chirwa", "Civil Engineers", "Utility Contractors"],
    },
    {
      id: "construction",
      title: "House Construction",
      description: "Individual house construction and community facilities development",
      startDate: "Jan 2022",
      endDate: "Oct 2022",
      duration: "10 months",
      status: "completed" as const,
      milestones: [
        {
          id: "phase1-houses",
          title: "Phase 1 Houses (20 units)",
          date: "Apr 30, 2022",
          description: "First phase of 20 houses completed and ready for occupancy",
          status: "completed" as const,
          icon: <Building2 className="h-4 w-4 text-primary" />,
        },
        {
          id: "clubhouse",
          title: "Community Clubhouse",
          date: "Jul 15, 2022",
          description: "Community clubhouse and recreational facilities completed",
          status: "completed" as const,
          icon: <Building2 className="h-4 w-4 text-primary" />,
        },
        {
          id: "phase2-houses",
          title: "Phase 2 Houses (30 units)",
          date: "Oct 20, 2022",
          description: "Second phase of 30 houses completed",
          status: "completed" as const,
          icon: <Building2 className="h-4 w-4 text-primary" />,
        },
      ],
      deliverables: [
        "50 completed housing units",
        "Community clubhouse",
        "Recreational facilities",
        "Security infrastructure",
        "Landscaping completion",
      ],
      team: ["Michael Phiri", "Patricia Kamoto", "Construction Teams", "Interior Designers"],
    },
    {
      id: "completion",
      title: "Final Delivery & Handover",
      description: "Final inspections, landscaping, and estate handover",
      startDate: "Nov 2022",
      endDate: "Jan 2023",
      duration: "3 months",
      status: "completed" as const,
      milestones: [
        {
          id: "landscaping",
          title: "Landscaping Completion",
          date: "Nov 30, 2022",
          description: "All landscaping and green spaces completed",
          status: "completed" as const,
          icon: <PenTool className="h-4 w-4 text-primary" />,
        },
        {
          id: "final-inspection",
          title: "Final Estate Inspection",
          date: "Dec 20, 2022",
          description: "Comprehensive estate inspection and quality verification",
          status: "completed" as const,
          icon: <ClipboardCheck className="h-4 w-4 text-primary" />,
        },
        {
          id: "handover",
          title: "Estate Handover",
          date: "Jan 15, 2023",
          description: "Official estate handover to homeowners association",
          status: "completed" as const,
          icon: <Key className="h-4 w-4 text-primary" />,
        },
      ],
      deliverables: [
        "Estate completion certificate",
        "Homeowner documentation",
        "Maintenance manuals",
        "Warranty certificates",
        "Community management setup",
      ],
      team: ["James Mbewe", "Grace Mwale", "Patricia Kamoto", "Community Management"],
    },
  ],
  // Add more project timelines as needed...
}
